### ISSUE TITLE
Problema do site ficando todo verde

### ISSUE THREAD

**Issue by rogeriorrodrigues** [rogeriorrodrigues/eShopWebDemosActions#19]
### Problema de cores

Durante o uso do site, eu vi que quando clico no botão de finalizar compra, ele fica todo verde e não aparece mais nada.

Passos para chegar ao erro que eu vi:
- [ ] selecione um produto
- [ ] Adicione a quantidade ao carrinho
- [ ] Clique em finalizar compra
- [ ] veja o erro!

![image](https://github.com/rogeriorrodrigues/eShopWebDemosActions/assets/6625448/0baa27d0-4f3a-4f62-be0c-0b37d07b9ba4)

<img width="601" alt="Screenshot 2023-03-24 170521" src="https://github.com/rogeriorrodrigues/eShopWebDemosActions/assets/6625448/def208b8-078b-4b9f-b272-63bb2687a2f4">

@rogeriorrodrigues veja esse problema

#10 
#9

**Comment by rogeriorrodrigues** [comment]
Blz pessoal, encontrei o problema e vou resolver.
