### ISSUE TITLE
Problema do site ficando todo verde

### ISSUE THREAD

**Issue by ClarissaDamasceno** [rogeriorrodrigues/eShopWebDemosActions#23]
### Problema de cores

Durante o uso do site, eu vi que quando clico no botão de finalizar compra, ele fica todo verde e não aparece mais nada.

Passos para chegar ao erro que eu vi:
- [ ] selecione um produto
- [ ] adicione a quantidade ao carrinho
- [ ] clique em finalizar compra
- [ ] veja o erro

![image](https://github.com/rogeriorrodrigues/eShopWebDemosActions/assets/71802397/2f14f201-cc1d-4c73-b414-ece1f14151a9)

@rogeriorrodrigues veja esse problema

#9
